server {
  listen 80;

  location / {
    proxy_pass http://shell-app:80;
  }

  location /mf/flow-builder/ {
    proxy_pass http://flow-builder-mf:80/;
  }

  location /mf/campaign-manager/ {
    proxy_pass http://campaign-manager-mf:80/;
  }

  location /mf/user-manager/ {
    proxy_pass http://user-manager-mf:80/;
  }

  location /mf/analytics-dashboard/ {
    proxy_pass http://analytics-dashboard-mf:80/;
  }
}

